### ISSUE TITLE
在mpvue下使用报错

### ISSUE THREAD

**Issue by mushan0x0** [skyujilong/tinypng-webpack-plugin#2]
`png-webpack-plugin/index.js:35
        compiler.hooks.emit.tapPromise(this.pluginName,(compilation)=>{
                       ^

TypeError: Cannot read property 'emit' of undefined`

**Comment by skyujilong** [comment]
which webpack version do you use ?  

# for webpack 4
```
$ npm install tinypng-webpack-plugin --save-dev
```
# for webpack 3 & 2 & 1
```
$ npm install tinypng-webpack-plugin@1.0.2 --save-dev
```

**Comment by mushan0x0** [comment]
谢谢，虽然没有报错了，但还是没有上传压缩图片。

**Comment by skyujilong** [comment]
you can try a big *.png or *.jpg. because , if you use a url-loader to load img, it can base64 small img. 
ok close.

**Comment by mushan0x0** [comment]
mpvue没有使用url-loader，也没有把图片转成base64，它只是单纯地移动了img文件夹
