### ISSUE TITLE
添加对已压缩图片不进行重复压缩的功能

### ISSUE THREAD

**Issue by 791045873** [skyujilong/tinypng-webpack-plugin#3]
如果只是使用tinyPng的免费额度。每次打包都压缩一遍文件会导致免费额度很快用完，最好能添加一个对已压缩图片不进行重复压缩的功能。

**Comment by skyujilong** [comment]
1.0.2版本 以及2.0.0 版本都支持本地的缓存。如果你们经常删除node_modules的话，会导致缓存失败。走缓存不会走tinypng的压缩额度。
